server:
  port: 8091
logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: TRACE
    org.hibernate: DEBUG
    com.mysql.cj: DEBUG
    org.springframework.security: debug
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: selfcloud-announcement
  h2:
    console:
      enabled: true
  datasource:
    username: ${ANNOUNCEMENTS_DB_USERNAME:announcements}
    password: ${ANNOUNCEMENTS_DB_PASSWORD:announcements}
    url: jdbc:mysql://${ANNOUNCEMENTS_HOST_IP:localhost}:3306/announcements
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    enabled: true
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}

    serviceUrl:
      defaultZone:  http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    prefer-ip-address: 'true'

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${KAFKA_HOST:localhost}:9092
  zookeeper:
    connection:
      string: ${ZOOKEEPER_HOST:localhost}:2181
